<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbqnibv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbqnibv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKbqnibv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKbqnibv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKbqnibv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kbqnibv',
    'container.build_id' => 'e31443f1',
    'container.build_time' => 1526631237,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbqnibv');
